// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipcctrbzlihztattqcjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwY2N0cmJ6bGloenRhdHRxY2ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzkyMTAsImV4cCI6MjA2MDgxNTIxMH0.Vf51Gsd0ueetdKCaLYrXlcFIsPTzG3Hf2jdQ4HBwI0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);